#!/bin/sh
set -e

if [ "$1" = configure ]; then

    getent group dureporter >/dev/null 2>&1 || groupadd -r dureporter
    getent passwd dureporter >/dev/null 2>&1 || \
        useradd -r -g dureporter -d /var/lib/dumeter-reporter -s /sbin/nologin \
            -c "dumeter.net reporter" dureporter >/dev/null 2>&1 || exit 1
    chown -R dureporter:dureporter /var/lib/dumeter-reporter

fi

#DEBHELPER#

exit 0
